/*
Deployment script for ClassExample

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ClassExample"
:setvar DefaultFilePrefix "ClassExample"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Categories].[Namr] (SqlSimpleColumn) will not be renamed to Name';


GO
PRINT N'Altering [dbo].[FAQS]...';


GO
ALTER TABLE [dbo].[FAQS]
    ADD [Category_id] INT NULL;


GO
PRINT N'Creating [dbo].[FK_FAQS_ToCategory]...';


GO
ALTER TABLE [dbo].[FAQS] WITH NOCHECK
    ADD CONSTRAINT [FK_FAQS_ToCategory] FOREIGN KEY ([Category_id]) REFERENCES [dbo].[Categories] ([Id]);


GO
